from .kalori_mingguan_widget import KaloriMingguanWidget
from .komposisi_gizi_widget import KomposisiGiziWidget
from .detail_makro_widget import DetailMakroWidget
from .top_makanan_widget import TopMakananWidget
from .nav_card_widget import NavCardWidget
from .fun_fact_widget import FunFactWidget
from .kalori_hari_ini_widget import KaloriHariIniWidget
